Buttons = [
 {"tipo":"operacion", "valor":"**", "texto":"exp"},
 {"tipo":"operacion", "valor":"sqr", "texto":"sqr "},
 {"tipo":"trigger", "valor":"c", "texto":"c"},
 {"tipo":"trigger", "valor":"Ce", "texto":"Ce"},
 {"tipo":"operacionPrefija", "valor":"**2", "texto":"exp2"},
 {"tipo":"operacionPrefija", "valor":"sqr2", "texto":"sqr2"},
 {"tipo":"operacionPrefija", "valor":"!", "texto":"!"},
 {"tipo":"operacionPrefija", "valor":"1/x", "texto":"1/x"},
 {"tipo":"numero", "valor":2.71828, "texto":"e"},
 {"tipo":"numero", "valor":3.1415, "texto":"π"},
 {"tipo":"numero", "valor":1.61803, "texto":"phi"},
 {"tipo":"operacion", "valor":"/", "texto":"/"},
 {"tipo":"numero", "valor":7, "texto":"7"},
 {"tipo":"numero", "valor":8, "texto":"8"},
 {"tipo":"numero", "valor":9, "texto":"9"},
 {"tipo":"operacion", "valor":"*", "texto":"*"},
 {"tipo":"numero", "valor":4,"texto":"4"},
 {"tipo":"numero", "valor":5,"texto":"5"},
 {"tipo":"numero", "valor":6,"texto":"6"},
 {"tipo":"operacion", "valor":"-", "texto":"-"}, 
 {"tipo":"numero", "valor":1, "texto":"1"},
 {"tipo":"numero", "valor":2, "texto":"2"},
 {"tipo":"numero", "valor":3, "texto":"3"},
 {"tipo":"operacion", "valor":"+", "texto":"+"},
 {"tipo":"operacion", "valor":"log", "texto":"log"},
 {"tipo":"numero","valor":0, "texto":"0"},
 {"tipo":"trigger","valor":".","texto":"."},
 {"tipo":"trigger","valor":"=","texto":"="}
]